language: python
python:
  - "2.6"

install:
  - cd buildouts/plone4
  - ./install.sh
  - bin/buildout

script:
  - bin/test

notifications:
  email:
    recipients:
      - eea-github@googlegroups.com
