#!/bin/sh

red="\e[1;31m"
green="\e[1;32m"
yellow="\e[1;33m"
blue="\e[1;34m"
NC="\e[0m" # No Color


GUESS_BUILD="../../bin/sphinx-build"


get_abs_path()
{
    local  __resultvar=$2
    local  the_result=$(cd `dirname "$1"` && pwd)/`basename "$1"`
    eval $__resultvar="'$the_result'"
}

eval set -- $(getopt -n $0 -o "" -l "help" -l "debug" -l "clean" -- "$@")
declare debug clean help
declare -a paths


while [ $# -gt 0 ] ; do
    case "$1" in
    --clean) clean=1 ; shift ;;
    --debug) debug=1 ; shift ;;
     --help) help=1 ; shift ;;
         --) shift ;;
         -*) echo "bad option '$1'" ; exit 1 ;;
          *) paths=("${paths[@]}" "$1") ; shift ;;
    esac
done

if [ ! -z "$help" ]; then
    echo "Usage: ./build [options] [/path/to/sphinx-build]"
    echo "When run without arguments, attempts to find sphinx-build in buildout folder (../../) or fails."
    echo "Options:"
    echo "      --clean                   -- make clean before building"
    echo "      --debug                   -- do nothing, print debug data"
    echo "      --help                    -- print this message"
    exit 0
fi


GIVEN_PATH="${paths[0]}"

if [ -z "$GIVEN_PATH" ]; then
    echo -e "[${blue}I${NC}] sphinx-build not specified, attempting to find it..."
    if [ -f "$GUESS_BUILD" ]; then
        get_abs_path "$GUESS_BUILD" SPHINXBUILD
        echo -e "[${blue}I${NC}] Found in ${green}$SPHINXBUILD${NC} !"
    else
        echo "Need path to sphinx-build executable"
        exit 1
    fi
else
    if [ ! -f "$GIVEN_PATH" ]; then
        echo -e "[${red}E${NC}] ${red}The provided sphinx-build path is invalid!${NC}"
        exit 1
    else
        get_abs_path "$GIVEN_PATH" SPHINXBUILD
    fi
fi

echo "........................................................................................."
echo ""
echo -e "[${blue}I${NC}] Using Sphinx from: ${green}$SPHINXBUILD${NC}"
echo ""

BUILDDIR="$(pwd)"
SOURCEDIR="$BUILDDIR/src"

if [ ! -z "$debug" ]; then
    echo -e "[${yellow}D${NC}] SPHINXBUILD=$SPHINXBUILD"
    echo -e "[${yellow}D${NC}] BUILDDIR=$BUILDDIR"
    echo -e "[${yellow}D${NC}] SOURCEDIR=$SOURCEDIR"
else
    if [ -z "$debug" ]; then
        if [ ! -z "$clean" ]; then
            make clean SPHINXBUILD=$SPHINXBUILD BUILDDIR=$BUILDDIR SOURCEDIR=$SOURCEDIR
        fi
        make html SPHINXBUILD=$SPHINXBUILD BUILDDIR=$BUILDDIR SOURCEDIR=$SOURCEDIR
    else
        echo -e "[${blue}I${NC}] Debug enabled, doing nothing!"
        echo ""
    fi
fi

